[package]
name = "promo_input"
version = "0.1.0"
authors = ["the_r"]
edition = "2018"

[dependencies]
serde = "1.0.113"
serde_json = "1.0.55"
serde_derive = "1.0.113"
csv = "1.1.3"
xml_sheet_reader = { git = "https://github.com/RedHelmut/xml_sheet_reader.git" }
chrono = "0.4.11"
zip = "0.5.6"
